name: Webhook Trigger on Commit to Main

on:
  push:
    branches:
      - main

jobs:
  webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Call Webhook on Commit to Main
        run: |
          curl -X GET ${{ secrets.WEBHOOK_URL }}
